config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  get '/users/:id/dashboard', to: 'users#dashboard', as: :dashboard
  resources :users, only: [:new, :create, :show, :edit, :update]

  #get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_omniauth'

  get '/stories/dusty', to: 'stories#dusty', as: :dusty_stories

  get '/stories/:id/silly', to: 'stories#silly', as: :silly

  get '/stories/:id/details', to: 'stories#details'

  get '/prompts/random', to: 'prompts#random'

  resources :stories, only: [:index, :new, :create, :show, :edit, :update] do
    resources :submissions, only: [:index, :create, :edit, :update]
  end

  resources :prompts, only: [:index, :new, :create]

  resources :teams, only: [:index, :new, :create, :show]


  post '/join' => 'memberships#create'

end

app/models/user.rb
class User < ApplicationRecord
	has_many :memberships
	has_many :teams, through: :memberships
	has_many :submissions
	has_many :stories, through: :submissions
	has_many :prompts
	
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true

	def unique_stories
		stories.uniq
	end

	def public_stories
		unique_stories.select {|story| story.public}
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :verify_user, only: [:new, :create]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to dashboard_path(@user)
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
	end

	def update
	end

	def dashboard
		@teams = current_user.teams
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/views/users/_stories.html.erb
<%= link_to story_path(story.id) do %>
	<%= content_tag(:h4, story.title) %>
<% end %>
<%= tag.br %>
<%= content_tag(:p, story.description) %><%= tag.br %>
<%= content_tag(:h5, "Team: #{story.team_name}") %><%= tag.br %>

app/views/users/_team.html.erb
<%= link_to team_path(team.id) do %>
	<%= content_tag(:h4, team.name) %>
<% end %>

app/views/users/_teams.html.erb
<%= link_to team_path(team.id) do %>
	<%= content_tag(:h4, team.name) %>
<% end %>

app/views/users/dashboard.html.erb
<%= content_tag(:h2, "Welcome, #{current_user.name}") %>

<%= content_tag(:h3, "Your Stories") %>
<%= render(partial: "stories/story", collection: current_user.unique_stories) || "You haven't contributed to any stories yet." %><%= tag.br %>

<%= link_to "Stories in Need of Attention", dusty_stories_path %><%= tag.br %>
<%= link_to "Start a New Story", new_story_path %><%= tag.br %>

<%= button_tag "Show Writing Prompts", class: "js-prompts" %><%= tag.br %>
<div id="prompt_box"></div>
<%= link_to "Submit a Prompt", new_prompt_path %><%= tag.br %>

<%= content_tag(:h3, "Your Teams") %>
<%= render @teams || "You haven't joined any teams yet." %><%= tag.br %>
<%= content_tag(:h3, "Open Team Browser") %>

<%= link_to "Find a Team to Join", teams_path %><%= tag.br %>
<%= link_to "Start a Team", new_team_path %><%= tag.br %>

<%= link_to "Your Profile", user_path(current_user) %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><%= tag.br%>
	<%= f.label :email %>
	<%= f.text_field :email %><%= tag.br%>
	<%= f.label :password %>
	<%= f.password_field :password %><%= tag.br%>
	<%= f.label :password_confirmation, "Confirm Password" %>
	<%= f.password_field :password_confirmation %><%= tag.br%>

	<%= f.submit "Submit" %>
<% end %>

<%= content_tag(:p, "Already a user?") %> <%= link_to "Log In", login_path %>

app/views/users/show.html.erb
<%= content_tag(:h2, @user.name) %>
<%= content_tag(:p, @user.email) %>

<%= content_tag(:h3, "Stories:") %>
<%= render(partial: "stories/story", collection: @user.public_stories) || "This user hasn't contributed to any stories yet." %><%= tag.br %>