config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  get '/users/:id/dashboard', to: 'users#dashboard', as: :dashboard
  resources :users, only: [:new, :create, :show, :edit, :update]

  #get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_omniauth'

  get '/stories/dusty', to: 'stories#dusty', as: :dusty_stories

  get '/stories/:id/silly', to: 'stories#silly', as: :silly

  get '/stories/:id/details', to: 'stories#details'

  get '/prompts/random', to: 'prompts#random'

  resources :stories, only: [:index, :new, :create, :show, :edit, :update] do
    resources :submissions, only: [:index, :create, :edit, :update]
  end

  resources :prompts, only: [:index, :new, :create]

  resources :teams, only: [:index, :new, :create, :show]


  post '/join' => 'memberships#create'

end

app/models/submission.rb
class Submission < ApplicationRecord
	belongs_to :story
	belongs_to :user

	validates :content, presence: true, length: {maximum: 2000, too_long: "%{count} characters is the maximum allowed"}

	scope :older, -> { where("updated_at < ?", 2.days.ago) }

	def self.recent_stories
		last(5).collect{|submission| submission.story}.uniq.reverse
	end

	def self.by_story_and_user(story_id, user_id)
		where(story_id: story_id, user_id: user_id)
	end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

	def index
		@story = Story.find(params[:story_id])
		@submissions = Submission.by_story_and_user(params[:story_id], session[:user_id])
	end

	def create
		@story = Story.find(params[:story_id])
		@submission = @story.submissions.build(submission_params)
		if @submission.save
			render json: @submission, status: 201
		else
			render :new
		end
	end

	def edit
		@story = Story.find(params[:story_id])
		@submission = Submission.find(params[:id])
	end

	def update
		@story = Story.find(params[:story_id])
		@submission = Submission.find(params[:id])
		@submission.update(submission_params)
		redirect_to story_path(@story)
	end



	private

	def submission_params
		params.require(:submission).permit(:content, :user_id)
	end

end

app/views/submissions/_form.html.erb
<%= form_for [@story, @submission] do |f| %>
	<%= render partial: "application/errors", locals: {object: @submission} %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :story_id, value: @story.id %>
	<%= f.text_area :content %>
	<%= f.submit "Add to Story", data: { disable_with: false } %>
<% end %>

app/views/submissions/edit.html.erb
<%= content_tag(:h1, "Edit Your Contribution") %>
<%= render 'form' %>

app/views/submissions/index.html.erb
<%= content_tag(:h1, "Your Submissions to #{@story.title}") %>
<% @submissions.each do |submission| %>
	<%= content_tag(:p, submission.content) %>
	<%= link_to "Edit this Submission", edit_story_submission_path(@story, submission) %>
<% end %>