config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  get '/users/:id/dashboard', to: 'users#dashboard', as: :dashboard
  resources :users, only: [:new, :create, :show, :edit, :update]

  #get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_omniauth'

  get '/stories/dusty', to: 'stories#dusty', as: :dusty_stories

  get '/stories/:id/silly', to: 'stories#silly', as: :silly

  get '/stories/:id/details', to: 'stories#details'

  get '/prompts/random', to: 'prompts#random'

  resources :stories, only: [:index, :new, :create, :show, :edit, :update] do
    resources :submissions, only: [:index, :create, :edit, :update]
  end

  resources :prompts, only: [:index, :new, :create]

  resources :teams, only: [:index, :new, :create, :show]


  post '/join' => 'memberships#create'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :verify_user
	helper_method :current_user
	helper_method :authenticated_user?

	skip_before_action :verify_user, only: [:welcome]

	def welcome
		@recent = Submission.recent_stories
		@random_prompt = Prompt.order("RANDOM()").first
	end

	private

	def current_user
		User.find_by(id: session[:user_id])
	end

	def authenticated_user?
		!!current_user
	end

	def verify_user
		redirect_to root_path unless authenticated_user?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def header_links
		if authenticated_user?
			link_to("Dashboard", dashboard_path(current_user.id)) +
			' ' +
			link_to("Log Out", logout_path, method: :post)
		else
			link_to("Sign Up", new_user_path) +
			' ' +
			(render partial: "sessions/form")
		end
	end
end

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this article from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/welcome.html.erb
<%= content_tag(:h3, "Recently Updated Stories") %>
<% @recent.each do |story| %>
	<%= link_to story.title, story_path(story) %>
	<%= content_tag(:p, story.description) %>
<% end %>

<%= link_to "Browse Public Stories", stories_path %><%= tag.br %>

<%= content_tag(:h3, "Something to Write About:") %>
<%= content_tag :div, id: "random_prompt" do %>
	<%= content_tag(:p, @random_prompt.content) %>
<% end %>
<%= button_tag "Generate Another Prompt", id: "prompt_generator" %>